### PR TITLE
[TASK] Set a PHP version dependency

### PR DESCRIPTION
**Pull request by liayn**
Also remove the static version number in composer.json
as this is not recommended and is always deduced from the
tags of the repository.

### CODE REVIEW

**Comment by fnagel** [comment]
Thanks for the PR! 

Just for my curiosity: Is there a special reason for using PHP < 7.1?

**Comment by liayn** [comment]
Regarding PHP. Do you know by now whether the ext will work with 7.1? I would say no. So I would not declare a compatibility that might not be true. In the end that would cause only frustration by the user

**Comment by fnagel** [comment]
> Do you know by now whether the ext will work with 7.1?

No, no testing with 7.x so far -- that's why I was curious why you added this. I will remove this on merge.

**Comment by liayn** [comment]
??

**Comment by liayn** [comment]
I exclude PHP 7.1 explicitly.

**Comment by fnagel** [comment]
Which includes PHP 7.0 -- did you test that?

**Comment by liayn** [comment]
I looked at the code and found nothing contradicting. And it's running locally here on my 7.6 installation with PHP7 ;-)

**Comment by fnagel** [comment]
Good enough for now :-D 

Thanks for the info!

**Pull request closed without merging**
